### ISSUE TITLE
The auto-approval in TF is preventing builds from completing.

### ISSUE THREAD

**Issue by yoshinori-hardy** [dpires/jenkins-terraform-plugin#7]
Jenkins - 2.89.4
Terraform Plugin - 1.0.9
Terraform => 0.11.0
centos - 7

Version 0.11.0 of terraform introduced an auto-approval flag and this is preventing my build from completing.

see the jenkins log output:

```
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.

Enter a value:

Apply cancelled.

FATAL: java.lang.Exception: Terraform Apply failed: 1
	at org.jenkinsci.plugins.terraform.TerraformBuildWrapper.executeApply(TerraformBuildWrapper.java:249)
	at org.jenkinsci.plugins.terraform.TerraformBuildWrapper.setUp(TerraformBuildWrapper.java:269)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Finished: FAILURE
```

rolling back to version 0.10.8 resolved my issue.

**Comment by yoshinori-hardy** [comment]
from the Hashicorp docs an auto approve flag can be added to handle this

"terraform apply -input=false -auto-approve"

https://www.terraform.io/guides/running-terraform-in-automation.html#terraform-apply-input-false-auto-approve

**Comment by sebas-w** [comment]
I'm currently having this same issue when trying to use the built in freestyle terraform plugin options. There is nothing that allows a user to auto-approve without scrapping this method and building a pipeline for your project manually.

Would it be possible to add an option for -auto-approval?

**Comment by ritwik-singh-yash** [comment]
I have the same issue.
As we cannot run any terraform command in this , how can this be resolved?

**Comment by dpires** [comment]
I'm looking for a solution that will be backwards compatible with < 0.10.0 as with the addition of -auto-approve, also came the deprecation of -force on destroy (replaced with -auto-approve). 

Once I figure out a checkbox solution for both, i'll make a release.
